### ISSUE TITLE
Code explanations

### ISSUE THREAD

**Issue by LokartBC** [kazuhikoarase/kaleidoscope#2]
Hi !
I am making a different kind of kaleidoscope of my own, and I would be very interested in understanding a bit more about what your code does. Do you have any social link that I can contact you at to chat about it please ? Thanks a lot !

**Comment by kazuhikoarase** [comment]
Here is that. Doesn't think you?
Thank you.

**Comment by LokartBC** [comment]
@kazuhikoarase  Hey thanks for answering so fast, but I didn't understand what you said sorry, could you please reexplain ? thanks a lot !

**Comment by kazuhikoarase** [comment]
I think that GitHub is social place for me.

**Comment by LokartBC** [comment]
@kazuhikoarase Oh yeah sure, it is not practical to share pictures of math diagrams though but I can try :)

So say I have a source image with a point A in the image and a direction vector u. I would like to display this image on the canvas so the point A is displayed at the center of the canvas and the vector u matches some other direction vector v (bottom right diagonal for instance). Do you know what is the canvas transformation I need to do for that please ? 
Thanks a lot !

**Comment by LokartBC** [comment]
I think I found the formula !

**Comment by LokartBC** [comment]
@kazuhikoarase So I found the formula to do what I asked, thanks again :)
